ftpSetting:
  user: ${FTP_USER} 
  password : ${FTP_PASS} 
  location : ${FTP_LOCATION} 

ImageService:
  location: ${IMAGE_LOCATION} 
server:
    forward-headers-strategy: framework

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${DB_USER} 
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  activemq:
    broker-url: tcp://${ACTIVEMQ_HOST}:${ACTIVEMQ_PORT}
    user: ${ACTIVEMQ_USER} 
    password: ${ACTIVEMQ_PASS}
    
